plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  sass_dir: _sass
  style: compressed

url: "https://hiroakif93.github.io/rwiki"
baseurl: "/"

include:
  - _contents

affiliation:
  - Graduate School of Biostudies,
  - Center for Living Systems Information Science (CeLiSIS),
  - Kyoto University.
