# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"
gem "jekyll"
gem 'bootstrap', '~> 5.3.0'

group :jekyll_plugins do
    gem 'jekyll-sitemap'
    gem 'jekyll-feed'
    gem 'jekyll-seo-tag'
end